### ISSUE TITLE
TXTSearchTool with ollama

### ISSUE THREAD

**Issue by fre391** [crewAIInc/crewAI-tools#89]
Search is NOT limited to given txt file.

`
from crewai_tools import TXTSearchTool

txt_search_tool = TXTSearchTool(
    txt="kunst.txt",
    config=dict(
        llm=dict(
            provider="ollama", 
            config=dict(
                model="llama3.1",
            ),
        ),
        embedder=dict(
            provider="ollama", 
            config=dict(
                model="mxbai-embed-large",
            ),
        ),
    )
)
`

**Comment by iNLyze** [comment]
@fre391, nice solution, though I am not yet getting it to work. I am trying to apply the text tool to a local file like so:

```python
tool_txt_search = TXTSearchTool(
    txt=path/'nonsense.txt',
    config=config, 
    verbose=True
)
```
My config:

```python
config=dict(
    llm=dict(
        provider="ollama",  # Change this to your LLM provider
        config=dict(
            model="llama3.1",  # Specify the model you want to use
        ),
    ),
    embedder=dict(
        provider="ollama",  # Change this to your LLM provider
        config=dict(
            model="mxbai-embed-large",  # Specify the embedding model 
        ),
    ),
)
```

Running this from jupyter currently (on a server via ssh). Unfortunately, the instantiation never seems to finish. I am not seeing any text output and nothing in `journalctl -u ollama` either. 

How long does it take you to instantiate the tool? Any idea, why it might get stuck?

**Comment by kspviswa** [comment]
+ 1 . Also facing the same issue.

**Comment by siddas27** [comment]
```
semantic_search_resume = MDXSearchTool(mdx='./fake_doc.md',
    config=dict(
        llm=dict(
            provider="ollama", # Options include google, openai, anthropic, llama2, etc.
            config=dict(
                model="llama3.2",
                # Optional parameters can be included here.
                # temperature=0.5,
                # top_p=1,
                # stream=true,
            ),
        ),
        embedder=dict(
            provider="ollama", # or openai, ollama, ...
            config=dict(
                model="nomic-embed-text",
                # task_type="retrieval_document",
                # Optional title for the embeddings can be added here.
                # title="Embeddings",
            ),
        ),
    ))
```
For the above code, I am getting this error. Anyone got it working?
```
/Users/crewAI-tools/.venv/lib/python3.11/site-packages/embedchain/embedder/ollama.py:27: LangChainDeprecationWarning: The class `OllamaEmbeddings` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the :class:`~langchain-ollama package and should be used instead. To use it run `pip install -U :class:`~langchain-ollama` and import as `from :class:`~langchain_ollama import OllamaEmbeddings``.
  embeddings = OllamaEmbeddings(model=self.config.model, base_url=config.base_url)
Traceback (most recent call last):
  File "/Users/app.py", line 64, in <module>
    semantic_search_resume = MDXSearchTool(mdx='./fake_doc.md',
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/crewai_tools/tools/mdx_seach_tool/mdx_search_tool.py", line 32, in __init__
    super().__init__(**kwargs)
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/crewai_tools/tools/rag/rag_tool.py", line 47, in _set_default_adapter
    app = App.from_config(config=self.config) if self.config else App()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/embedchain/app.py", line 407, in from_config
    return cls(
           ^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/embedchain/app.py", line 124, in __init__
    self._init_db()
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/embedchain/app.py", line 152, in _init_db
    self.db._initialize()
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/embedchain/vectordb/chroma.py", line 74, in _initialize
    self._get_or_create_collection(self.config.collection_name)
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/embedchain/vectordb/chroma.py", line 106, in _get_or_create_collection
    self.collection = self.client.get_or_create_collection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/api/client.py", line 237, in get_or_create_collection
    return self._server.get_or_create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/api/segment.py", line 217, in get_or_create_collection
    return self.create_collection(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/api/segment.py", line 167, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 209, in create_collection
    existing = self.get_collections(name=name, tenant=tenant, database=database)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/crewAI-tools/.venv/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 435, in get_collections
    rows = cur.execute(sql, params).fetchall()
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: collections.topic
```

**Comment by kspviswa** [comment]
> I got everything working with this:
> 
> ```
> os.environ['OPENAI_API_BASE'] = 'http://localhost:11434'
> os.environ['OPENAI_MODEL_NAME'] = 'ollama/llama3.2'
> os.environ['OPENAI_API_KEY'] = 'NA'
> ```
> 
> Note: Using this will make this your default llm, no need to configure everything separately

Sorry not working. 

```
/.venv/lib/python3.12/site-packages/crewai/agent.py", line 161, in post_init_setup
    if env_var["key_name"] in unnacepted_attributes:
       ~~~~~~~^^^^^^^^^^^^
```

It is very clear that Ollama provider doesn't have a key called `key_name` . I wonder how it worked for you. Can you elaborate?

**Comment by kspviswa** [comment]
Ok I inspected the code and found that I had to upgrade crewai to latest version. Now it is working.
